version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - ./mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123456
      - MYSQL_DATABASE=eCommerce

  web:
    build: .
    working_dir: /code/src
    command: bash -c "sleep 30 && python manage.py collectstatic --noinput
                      && python manage.py makemigrations  && python manage.py migrate
                      && python manage.py loaddata products/fixtures/products.json
                      && echo "from django.contrib.auth import get_user_model; \
                               User = get_user_model(); \
                               User.objects.create_superuser('admin@gmail.com', password='mydjango')" | python manage.py shell
                      && gunicorn --config=gunicorn_config.py ecommerce.wsgi:application"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:web
