# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recommendations.custom_fileds


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_auto_20180406_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', recommendations.custom_fileds.RatingField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[recommendations.custom_fileds.validate_rating])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
