# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_userproductrating_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproductrating',
            options={'ordering': ['timestamp']},
        ),
    ]
