# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailactivation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailactivation',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='guestemail',
            old_name='update',
            new_name='updated',
        ),
    ]
