# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-04 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewed',
            options={'ordering': ['-timestamp'], 'verbose_name': 'object viewed', 'verbose_name_plural': 'objects viewed'},
        ),
    ]
